sudo: false
language: ruby
cache: bundler

branches:
  only:
    - master

rvm:
  - 2.3.1
  - 2.2.5
env:
  - RAILS_VERSION=5.0.0 ELASTICSEARCH_RUBY_VERSION=2.0.0 ELASTICSEARCH_RAILS_VERSION=0.1.9 SUBDIR=es_rails_initializer
  - RAILS_VERSION=5.0.0 ELASTICSEARCH_RUBY_VERSION=1.1.0 ELASTICSEARCH_RAILS_VERSION=0.1.9 SUBDIR=es_rails_initializer
  - RAILS_VERSION=4.2.7 ELASTICSEARCH_RUBY_VERSION=2.0.0 ELASTICSEARCH_RAILS_VERSION=0.1.9 SUBDIR=es_rails_initializer
  - RAILS_VERSION=4.2.7 ELASTICSEARCH_RUBY_VERSION=1.1.0 ELASTICSEARCH_RAILS_VERSION=0.1.9 SUBDIR=es_rails_initializer

before_install: gem install bundler -v 1.12.5

install: cd $TRAVIS_BUILD_DIR/$SUBDIR && bundle install --jobs=3 --retry=3

script: cd $TRAVIS_BUILD_DIR/$SUBDIR && bundle exec rake
